---
title: "College Scorecard Report"
author: "Ziao Lu, Lydia Maher, and Thomas Sun"
date: "December 1, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

In this report we assess the performance of publicly funded schools to determine the allocation of grant money for policymakers. Specifically, we attempt to identify the best schools in the US in terms of their demographic, academic, and socioeconomic characteristics in order to help increase equity and graduation rates for underserved populations. Additionally, we use predictive modeling techniques to find the determinants for graduation rates and post-graduation income.  We use ridge regression, lasso regression, principal components regression, and partial least squares regression applied to data on US universities from College Scorecard provided by the US department of education. We find the best fitting model to make accurate predictons on graduation and income. We find that 
