\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

\section*{Data}
To perform our analyses, we use data from College Scorecard, provided by the US Department of Education. The full College Scorecard dataset contains extensive data on characteristics and indicators for all federal financial aid eligible schools in the US every year for the past several years. For the purpose of our study, we select several variables that we deemed relevant to determining performance of a school. These are: total number of students, race, four year completion rate, cost of attendance, first generation status, income, and threshold earnings.


\end{document}